[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_API_URL = "https://api.example.com"

[[plugins]]
  package = "@netlify/plugin-nextjs" 